# Generated by Django 3.0 on 2020-01-31 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custemer',
            new_name='Customers',
        ),
    ]
